const FIELD_TYPE_STRING = 'string'
const FIELD_TYPE_DATE = 'date'
const FIELD_TYPE_ENUM = 'enum'
const FIELD_TYPE_ORGAN = 'organ'

const CONTENT_TYPE_JSON = 'application/json'

const FIELD_TYPES = [FIELD_TYPE_ENUM, FIELD_TYPE_STRING, FIELD_TYPE_DATE, FIELD_TYPE_ORGAN]
export {
  FIELD_TYPE_STRING,
  FIELD_TYPE_DATE,
  FIELD_TYPE_ENUM,
  FIELD_TYPE_ORGAN,
  FIELD_TYPES,
  CONTENT_TYPE_JSON
}
